import os

folders = []

folders.append('trunk/MCEVS/__pycache__')
folders.append('trunk/MCEVS/Analyses/__pycache__')
folders.append('trunk/MCEVS/Analyses/Aerodynamics/__pycache__')
folders.append('trunk/MCEVS/Analyses/Aerodynamics/BEMT/__pycache__')
folders.append('trunk/MCEVS/Analyses/Energy/__pycache__')
folders.append('trunk/MCEVS/Analyses/Geometry/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/Climb/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/Cruise/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/Descent/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/Hover/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/HoverClimb/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/HoverDescent/__pycache__')
folders.append('trunk/MCEVS/Analyses/Power/Others/__pycache__')
folders.append('trunk/MCEVS/Analyses/Stability/__pycache__')
folders.append('trunk/MCEVS/Analyses/Weight/__pycache__')
folders.append('trunk/MCEVS/Analyses/Weight/Battery/__pycache__')
folders.append('trunk/MCEVS/Analyses/Weight/Equipment/__pycache__')
folders.append('trunk/MCEVS/Analyses/Weight/Propulsion/__pycache__')
folders.append('trunk/MCEVS/Analyses/Weight/Structure/__pycache__')
folders.append('trunk/MCEVS/Applications/__pycache__')
folders.append('trunk/MCEVS/Applications/OpenVSP/__pycache__')
folders.append('trunk/MCEVS/Applications/OpenVSP/Components/__pycache__')
folders.append('trunk/MCEVS/Constants/__pycache__')
folders.append('trunk/MCEVS/Constants/Atmosphere/__pycache__')
folders.append('trunk/MCEVS/Constants/Gravity/__pycache__')
folders.append('trunk/MCEVS/Methods/__pycache__')
folders.append('trunk/MCEVS/Missions/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Climb/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Cruise/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Descent/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Hover/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/HoverClimb/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/HoverDescent/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Transition/__pycache__')
folders.append('trunk/MCEVS/Missions/Segments/Others/__pycache__')
folders.append('trunk/MCEVS/Optimization/__pycache__')
folders.append('trunk/MCEVS/Optimization/Gradient_Based/__pycache__')
folders.append('trunk/MCEVS/Optimization/Gradient_Free/__pycache__')
folders.append('trunk/MCEVS/Optimization/Surrogate_Based/__pycache__')
folders.append('trunk/MCEVS/Utils/__pycache__')
folders.append('trunk/MCEVS/Vehicles/__pycache__')
folders.append('trunk/MCEVS/Vehicles/Components/__pycache__')

folders.append('examples/power_estimation/reports/')
folders.append('examples/power_estimation/power_vs_speed/multirotor/reports/')
folders.append('examples/power_estimation/power_vs_speed/liftcruise/reports/')
folders.append('examples/bemt_validation/reports/')
folders.append('examples/energy_estimation/reports/')
folders.append('examples/mtow_estimation/reports/')
folders.append('examples/optimization/liftcruise/reports/')
folders.append('examples/optimization/multirotor/reports/')
folders.append('examples/range_speed_sweep/liftcruise/reports/')
folders.append('examples/range_speed_sweep/multirotor/reports/')
folders.append('examples/bemt_validation/APC_propellers/ThinElectric_10x5/reports/')
folders.append('examples/bemt_validation/APC_propellers/ThinElectric_10x7/reports/')
folders.append('examples/bemt_validation/NASA_results/reports/')

folders.append('.DS_Store')
folders.append('docs/.DS_Store')
folders.append('docs/vsp_models/.DS_Store')
folders.append('docs/xdsm/.DS_Store')
folders.append('docs/controllers/.DS_Store')
folders.append('docs/flat_plate_drag/.DS_Store')
folders.append('docs/rotors/.DS_Store')
folders.append('docs/motors/.DS_Store')
folders.append('docs/rotor_vr12_ssca09/.DS_Store')
folders.append('examples/.DS_Store')
folders.append('examples/aerodynamics/.DS_Store')
folders.append('examples/aerodynamics/liftcruise/.DS_Store')
folders.append('examples/aerodynamics/multirotor/.DS_Store')
folders.append('examples/bemt_validation/.DS_Store')
folders.append('examples/bemt_validation/APC_propellers/.DS_Store')
folders.append('examples/energy_estimation/.DS_Store')
folders.append('examples/mtow_estimation/.DS_Store')
folders.append('examples/optimization/.DS_Store')
folders.append('examples/optimization/liftcruise/.DS_Store')
folders.append('examples/optimization/multirotor/.DS_Store')
folders.append('examples/power_estimation/power_vs_speed/.DS_Store')
folders.append('examples/vehicle_creation/.DS_Store')
folders.append('examples/mission_visualization/.DS_Store')
folders.append('sheets/.DS_Store')
folders.append('trunk/.DS_Store')
folders.append('trunk/MCEVS/.DS_Store')
folders.append('trunk/MCEVS/Analyses/Aerodynamics/BEMT/Airfoils/.DS_Store')
folders.append('trunk/MCEVS/Analyses/Power/.DS_Store')
folders.append('trunk/MCEVS/Applications/OpenVSP/.DS_Store')
folders.append('trunk/MCEVS/Vehicles/Components/.DS_Store')

folders.append('examples/vehicle_creation/LiftPlusCruise_NASA/.vsptime')
folders.append('examples/vehicle_creation/QuadRotor_NASA/.vsptime')
folders.append('examples/vehicle_creation/.vsptime')
folders.append('examples/mtow_estimation/.vsptime')
folders.append('examples/range_speed_sweep/multirotor/.vsptime')
folders.append('examples/range_speed_sweep/liftcruise/.vsptime')

folders.append('examples/mtow_estimation/openmdao_checks.out')
folders.append('examples/bemt_validation/openmdao_checks.out')

folders.append('examples/aerodynamics/multirotor/Unnamed_CompGeom.txt')
folders.append('examples/power_estimation/Unnamed_CompGeom.txt')
folders.append('examples/power_estimation/power_vs_speed/liftcruise/Unnamed_CompGeom.txt')
folders.append('examples/power_estimation/power_vs_speed/multirotor/Unnamed_CompGeom.txt')
folders.append('examples/energy_estimation/Unnamed_CompGeom.txt')
folders.append('examples/mtow_estimation/Unnamed_CompGeom.txt')
folders.append('examples/optimization/multirotor/Unnamed_CompGeom.txt')
folders.append('examples/range_speed_sweep/multirotor/Unnamed_CompGeom.txt')
folders.append('examples/range_speed_sweep/liftcruise/Unnamed_CompGeom.txt')

for folder in folders:
	try:
		os.system(f'rm -r {folder}')
	except:
		pass